### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by JeremyConnor** [paritytech/canvas-ui#21]
@seanyoung What can be the reason behind the error : 
```
contracts.putCode
createType(AccountId):: Maximum call stack size exceeded
```
I was able to upload a WASM and ABI file to canvas UI. After clicking on Sign and Submit, I get the above stated error.

**Comment by Robbepop** [comment]
Can you post us your `.wasm` and metadata files please?

**Comment by JeremyConnor** [comment]
My AssetTransfer.wasm file is : 
[AssetTransfer.zip](https://github.com/paritytech/canvas-ui/files/5458772/AssetTransfer.zip)

My ABI file(AssetTransfer.json) is :
```
{
  "contract": {
    "authors": [
      "unknown"
    ],
    "name": "AssetTransfer",
    "version": "0.0.1"
  },
  "metadataVersion": "0.1.0",
  "source": {
    "compiler": "solang 0.1.4",
    "hash": "0x7d163f445bec3d33e90d0f60bda40acd42f2760dbc1b731616af70a6001e05c7",
    "language": "Solidity 0.1.4"
  },
  "spec": {
    "constructors": [
      {
        "args": [],
        "docs": [
          ""
        ],
        "name": "new",
        "selector": "0x861731d5"
      }
    ],
    "events": [
      {
        "args": [
          {
            "indexed": false,
            "name": "_newUser",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          }
        ],
        "docs": [
          ""
        ],
        "name": "successfulRegistration"
      },
      {
        "args": [
          {
            "indexed": false,
            "name": "sender",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          },
          {
            "indexed": false,
            "name": "_hexAsset",
            "type": {
              "display_name": [
                "String"
              ],
              "type": 5
            }
          }
        ],
        "docs": [
          ""
        ],
        "name": "addedAsset"
      },
      {
        "args": [
          {
            "indexed": false,
            "name": "sender",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          },
          {
            "indexed": false,
            "name": "receiver",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          },
          {
            "indexed": false,
            "name": "hexOfAsset",
            "type": {
              "display_name": [
                "String"
              ],
              "type": 5
            }
          }
        ],
        "docs": [
          ""
        ],
        "name": "assetSent"
      }
    ],
    "messages": [
      {
        "args": [
          {
            "name": "_user",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          }
        ],
        "docs": [
          ""
        ],
        "mutates": false,
        "name": "viewBalance",
        "payable": false,
        "return_type": {
          "display_name": [
            "u256"
          ],
          "type": 1
        },
        "selector": "0xc1a13d1a"
      },
      {
        "args": [
          {
            "name": "_assetHex",
            "type": {
              "display_name": [
                "String"
              ],
              "type": 5
            }
          }
        ],
        "docs": [
          ""
        ],
        "mutates": false,
        "name": "findOwner",
        "payable": false,
        "return_type": {
          "display_name": [
            "AccountId"
          ],
          "type": 4
        },
        "selector": "0x63560a8e"
      },
      {
        "args": [
          {
            "name": "_hexAsset",
            "type": {
              "display_name": [
                "String"
              ],
              "type": 5
            }
          }
        ],
        "docs": [
          ""
        ],
        "mutates": true,
        "name": "addAsset",
        "payable": false,
        "return_type": null,
        "selector": "0xa7c6b52e"
      },
      {
        "args": [],
        "docs": [
          ""
        ],
        "mutates": true,
        "name": "receiveAsset",
        "payable": false,
        "return_type": {
          "display_name": [
            "String"
          ],
          "type": 5
        },
        "selector": "0xb2f3b5bc"
      },
      {
        "args": [
          {
            "name": "_assetHex",
            "type": {
              "display_name": [
                "String"
              ],
              "type": 5
            }
          },
          {
            "name": "_receiver",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          }
        ],
        "docs": [
          ""
        ],
        "mutates": true,
        "name": "sendAsset",
        "payable": false,
        "return_type": null,
        "selector": "0xd6e5288f"
      },
      {
        "args": [
          {
            "name": "_newUser",
            "type": {
              "display_name": [
                "AccountId"
              ],
              "type": 4
            }
          }
        ],
        "docs": [
          ""
        ],
        "mutates": true,
        "name": "register",
        "payable": false,
        "return_type": null,
        "selector": "0x4420e486"
      }
    ]
  },
  "storage": {
    "struct": {
      "fields": []
    }
  },
  "types": [
    {
      "def": {
        "primitive": "u256"
      }
    },
    {
      "def": {
        "primitive": "u8"
      }
    },
    {
      "def": {
        "array": {
          "len": 32,
          "type": 2
        }
      }
    },
    {
      "def": {
        "composite": {
          "fields": [
            {
              "type": 3
            }
          ]
        }
      },
      "path": [
        "AccountId"
      ]
    },
    {
      "def": {
        "primitive": "str"
      }
    }
  ]
}
```

**Comment by seanyoung** [comment]
The issue with `u256` is resolved by https://github.com/polkadot-js/api/pull/2752

**Comment by seanyoung** [comment]
Having said that I don't know what's wrong with the metadata.
@ascjones do you know what is wrong with the metadata? Thanks

**Comment by JeremyConnor** [comment]
> The issue with `u256` is resolved by [polkadot-js/api#2752](https://github.com/polkadot-js/api/pull/2752)

Ohkay, because initially it did state an error about not finding u256 but when I uploaded the same file twice or thrice, it worked. Also, I would like to bring into your notice that I tried with a sample flipper.wasm and flipper.json file. It tends to work fine sometimes and once a while gives this same Maximum Call Stack error.

**Comment by JeremyConnor** [comment]
@seanyoung  @Robbepop  Is there any solution for this? What is the reason behind this error?

**Comment by seanyoung** [comment]
@JeremyConnor is this the same contract code  as https://github.com/hyperledger-labs/solang/issues/300#issuecomment-717686144

I can deploy this contract correctly, and use the functions. However, the `findOwner` function does an `assert()` and if this fails, then I get the following error in the polkadot ui console:

Error: createType(AccountId):: Invalid AccountId provided, expected 32 bytes, found 29

The 29 bytes is the error "The asset doesn't exist!" (with one byte length and four bytes error selector 0x08c379a0).

I'm not sure how Solang should be returning error strings to the ui. Currently it calls `seal_return(1, ... )`` with the above error string and function selector).

@JeremyConnor is this what you are seeing?|
@Robbepop   how should Solang deal with failing asserts in its code? Note that Solidity has `try` .. `catch` to catch errors returned from `seal_call`.

**Comment by JeremyConnor** [comment]
@seanyoung  Yes that (https://github.com/hyperledger-labs/solang/issues/300#issuecomment-717686144) is the same contract that I am trying to deploy. Since I had not created a contracts pallet in the substrate therefore I used canvas UI to deploy the contract.  And using the canvas UI, I got the error "Maximum call stack size exceeded".

**Comment by JeremyConnor** [comment]
@seanyoung, In order to deploy the contract, I tried removing the require statements to not encounter any type of AccountID error, but still came across the same error. It is worth mentioning that I used the Canvas UI. Will it make any difference if I use Canvas UI and not the Polkadot UI? (I am using canvas UI because Polkadot requires a contract pallet, which I haven't used in my substrate-node-template)

**Comment by JeremyConnor** [comment]
@seanyoung I installed the contracts pallet and used Polkadot UI to deploy the contract, but there were few things that I noticed.

- I could not see any event getting triggered with the corresponding transaction. 
- I had created a check balance function which would display the balance of a person, but when I clicked on the view button, I could not see any result and moreover, the balance was 0 although I had initialised it to 1000.

**Comment by seanyoung** [comment]
@JeremyConnor thanks for testing solang, sorry for the delay getting back to you.

- Looks like `msg.sender` is broken which causing problems with AssetTransfer.sol, I'm looking into this
- Events aren't displayed yet, I think this is a limitation of the UI
- There are issues with the canvas-ui which I haven't figured out yet

I'm spending today looking at these issues, hope to have more for you later today

**Comment by JeremyConnor** [comment]
@seanyoung 
**Update on previous errors:** Thanks for looking into the issue. After spending a lot of time on Canvas UI and still facing the errors, I installed the Contracts pallet in the substrate node to deploy the smart contract using polkadot UI. When calling the receive() function, the asset should successfully be transferred to the ```msg.sender```, due to the following code
```
assetToOwner[send[msg.sender].hexOfAsset] = msg.sender;
```
 this works well when tested on the Remix IDE. But when deploying it on the Polkadot UI, the balance gets updated but the asset does not get transferred.

**Comment by seanyoung** [comment]
I'm working on fixing `msg.sender`, thank you for investigating!

**Comment by seanyoung** [comment]
The first problem I've discovered is that `msg.sender` is broken in read transactions: https://github.com/polkadot-js/apps/issues/3989

**Comment by seanyoung** [comment]
That issue with msg.sender doesn't explain the issue with receiveAsset() which you discovered.

**Comment by JeremyConnor** [comment]
The receiveAsset() function neither updates the ownership of the asset nor does it return any value as it is supposed to, when deployed using Polkadot UI. If this issue doesn't relate to msg.sender, then what can be a possible reason? I guess, maybe it's related to something other than msg.sender

**Comment by seanyoung** [comment]
I've fixed one issue: https://github.com/hyperledger-labs/solang/pull/309

**Comment by JeremyConnor** [comment]
@seanyoung Sorry for the late response. I installed the new solang and tried deploying my AssetTransfer.sol
I am getting the following error:
```wasm-ld : not found```.
![Screenshot from 2020-11-09 01-28-53](https://user-images.githubusercontent.com/73089748/98482985-05bad300-222b-11eb-89c9-50147ac56f70.png)

**Comment by seanyoung** [comment]
The latest solang requires wasm-ld for linking the wasm contract. This is because solidity function types are now supported, which requires function pointers and function pointer relocations in the linker. This is not supported by the simple linker solang was using, so I decided to switch to a proper linker. This will also allow some other optimizations.

You can install the `wasm-ld` linker by installing the lld package (or lld-10).

Ideally solang would use lld as a library and it would not depend on an external linker executable. I am working on fixing this here https://github.com/hyperledger-labs/solang/pull/302 unfortunately the lld library is totally not threadsafe which breaks the solang tests.

**Comment by JeremyConnor** [comment]
@seanyoung  I have installed lld-10, but I am still getting the same error.
To check if lld is installed I used the command ```ld.lld --version```. 
The terminal output was ```LLD 10.0.0 (compatible with GNU linkers)```

**Comment by seanyoung** [comment]
@JeremyConnor you needed wasm-ld, not ld.lld

However, the latest solang no longer needs the wasm-ld linker. It uses the linker as an llvm library. Please update your solang and it should "just work".

**Comment by JeremyConnor** [comment]
@seanyoung  It seems like there is some header file missing, or do I need to download it externally? I pulled the solang github repo and used ```cargo build --release```. This is when I get this error:
![Screenshot from 2020-11-10 00-13-28](https://user-images.githubusercontent.com/73089748/98583275-1f6f1f80-22ea-11eb-95a1-25189e35ca18.png)

**Comment by seanyoung** [comment]
You need the llvm linker library headers. You can download a precompiled version here: https://solang.readthedocs.io/en/latest/installing.html#installing-llvm-on-linux or use the dockerfile to build your own.

**Comment by JeremyConnor** [comment]
Hey @seanyoung ! I installed the llvm as you suggested and it worked. Also, the previous errors have been solved and now the mapping gets updated and so does the balance. 
Thanks for the help! It would be great we could see the events getting triggered by the contract in the UI (The events are not visible in the Polkadot.js UI).

**Comment by seanyoung** [comment]
@JeremyConnor thanks for testing that.

I agree, it would be very helpful to see the events in the canvas-ui, also it would be useful to see reverts/asserts with their reason string.. I've raised #24 and #23 for this.

**Comment by JeremyConnor** [comment]
> @JeremyConnor thanks for testing that.
> 
> I agree, it would be very helpful to see the events in the canvas-ui, also it would be useful to see reverts/asserts with their reason string.. I've raised #24 and #23 for this.

Yes, it will be really useful to see the string messages associated with the revert functions. It was great to see the issues I came across being worked upon here! Keep up the great work @seanyoung .

**Comment by seanyoung** [comment]
Thank you very much. 

Shall we close this issue then? Please do open another issue if you find something different.

**Comment by JeremyConnor** [comment]
> Thank you very much.
> 
> Shall we close this issue then? Please do open another issue if you find something different.

Yeah sure.
